volumes:
  ldap_data:
  ldap_config:
  sync_log:
  web_data:


services:
  ldap:
    image: osixia/openldap
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
    ports:
      - "389:389"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

  sync:
    build: .
    depends_on:
    restart: unless-stopped
      - ldap
    env_file:
      - ./.env
    environment:
      #- BAIKAL_URL=${BAIKAL_URL}
      #- BAIKAL_USERNAME=${BAIKAL_USERNAME}
      #- BAIKAL_PASSWORD=${BAIKAL_PASSWORD}
      - BAIKAL_URL
      - BAIKAL_USERNAME
      - BAIKAL_PASSWORD
    volumes:
      - sync_log:/var/log

  web: # used for provisioning
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - web_data:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"

