volumes:
  ldap_data:
  ldap_config:
  sync_log:
  web_data:


services:
  ldap:
    image: osixia/openldap
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "389:389"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

  sync:
    build: .
    depends_on:
      - ldap
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - sync_log:/var/log/carddav2ldap

  web: # used for provisioning
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - web_data:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"

  phpldapadmin:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ${LDAP_HOST}
      PHPLDAPADMIN_HTTPS: ${HTTPS}
    ports:
      - "${ADMIN_PORT}:80"
    depends_on:
      - ldap
